### ISSUE TITLE
`MACOSX_DEPLOYMENT_TARGET` does not work with `c_stdlib_version` set in the build of a package for MacOS

### ISSUE THREAD

**Issue by eunos-1128** [prefix-dev/rattler-build#1117]
I encountered an issue where the build of a package for MacOS failed because `MACOSX_DEPLOYMENT_TARGET` was not set to the same version, even though `c_stdlib_version` was set in the conda_build_config.yaml.

I don't know exactly why, but is this a kind of bug?

**Comment by wolfv** [comment]
Maybe @h-vetinari can comment on wether we need to set both values or if one should be enough. I am not sure!

**Comment by wolfv** [comment]
I believe you need to set both. But I am verifying with @h-vetinari and others. Thanks for testing!

**Comment by h-vetinari** [comment]
No, it should be enough to set just c_stdlib_version. We have logic in smithy that will still populate both values in the variant config though, because the CI setup still relies on MACOSX_DEPLOYMENT_TARGET.

We did update the logic in staged-recipes as well (which isn't using the general ci setup), I'd have to take a look what goes wrong there

**Comment by h-vetinari** [comment]
Did you open a PR for this already? I cannot find it on https://github.com/conda-forge/staged-recipes. It's possible that local builds are missing the logic I mentioned, but it should definitely be there for the actual CI runs.

**Comment by eunos-1128** [comment]
I've had opened https://github.com/conda-forge/staged-recipes/pull/27710, but changed to `conda-build` instead of `rattler-build` due to this error.

**Comment by eunos-1128** [comment]
When I used `variants.yaml` instead of `conda_build_config.yaml`, it didn't work.

**Comment by wolfv** [comment]
Yes, with `variants.yaml` the problem is that in staged-recipes the automation only looks at `conda_build_config.yaml` so it will never "magically" add the `MACOS_DEPLOYMENT_TARGET`...

**Comment by eunos-1128** [comment]
I see.

> No, it should be enough to set just c_stdlib_version. We have logic in smithy that will still populate both values in the variant config though, because the CI setup still relies on MACOSX_DEPLOYMENT_TARGET.
> 
> We did update the logic in staged-recipes as well (which isn't using the general ci setup), I'd have to take a look what goes wrong there

This means the problem ie fixed now?

**Comment by wolfv** [comment]
It's not fixed yet. We either need to support `variants.yaml` in conda-forge, or we need to support `conda_build_config.yaml` in rattler-build. :)

**Comment by wolfv** [comment]
We support `conda_build_config.yaml` files now, so I think this is fixed.

**Comment by eunos-1128** [comment]
@wolfv 

For some reason it seems to work with feedstocks.

https://github.com/conda-forge/cb-clipboard-feedstock/blob/main/recipe/variants.yaml

It seems that in `conda-forge/staged-recipes` repo cannot pick up the `c_stdlib_version` in both variants.yaml and conda_build_config.yaml.

https://github.com/conda-forge/staged-recipes/pull/29354/commits/38c652c179c33e11ce08c5f3aba18ac26dc876a5
